sonar.verbose=true
sonar.organization=mysonarqubeproject
sonar.projectKey=mysonarqubeproject-00_mysqproject
sonar.projectName=mySQproject
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
